apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    layer: db-layer
    app: demo-voting
    pod: redis
spec:
  template:
    metadata:
      name: redis-pod
      labels:
        layer: db-layer
        app: demo-voting
        pod: redis
    spec: 
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
  replicas: 1
  selector: 
    matchLabels:
      layer: db-layer
      app: demo-voting
      pod: redis
