apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    layer: db-layer
    app: demo-voting
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    layer: db-layer
    app: demo-voting
    pod: redis

