apiVersion: v1
kind: Service
metadata:
  name: result-app-service
  labels:
    layer: front-end
    app: demo-voting
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
  selector:
    layer: front-end-pod
    app: demo-voting
    pod: result-app
    
