apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
  labels:
    layer: front-end-pod
    app: demo-voting
    pod: voting-app
spec:
  template:
    metadata:
      name: voting-app-pod
      labels:
        layer: front-end-pod
        app: demo-voting
        pod: voting-app
    spec: 
      containers:
        - name: voting-app
          image: dockersamples/examplevotingapp_vote 
          ports:
            - containerPort: 80     
  replicas: 3
  selector: 
    matchLabels:
      layer: front-end-pod
      app: demo-voting
      pod: voting-app
