apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
    layer: front-end-pod
    app: demo-voting
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    layer: front-end-pod
    app: demo-voting
    pod: voting-app
